---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: tag_list
  name: tags
  label: Tags
  description: enter tags here
- type: file
  label: Featured Image
  name: featured_image
  description: Minimum 1280x720
  config:
    maxSize: '8'
  default: "/uploads/2018/02/07/calltoaction.jpg"
pages:
- content/blog/Test-2.md
- content/blog/Test-1.md
- content/blog/sds.md
